#!/usr/bin/env bash

# Update the package list and install Nginx with automatic "yes" answers to prompts
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '/server {/a \
    location /redirect_me {\
        return 301 https://www.example.com/new_page;\
    }' /etc/nginx/sites-available/default

sudo /etc/init.d/nginx restart
