#!/bin/bash
# Update the package list and install Nginx with automatic "yes" answers to prompts
sudo apt-get update
sudo apt-get install -y nginx

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}
EOF'
sudo /etc/init.d/nginx restart
