#!/usr/bin/env bash
#this file simple adds the header X-served-by to the nginx response

HEADER_NAME="X-Served-By"
HEADER_VALUE="$(hostname)"

NGINX_CONFIG="/etc/nginx/nginx.conf"

if [ -f "$NGINX_CONFIG" ]; then
    sed -i "/http {/a \ \ \ \ add_header $HEADER_NAME '$HEADER_VALUE';" "$NGINX_CONFIG"

    # Test the Nginx configuration for syntax errors
    if nginx -t; then
        # Reload Nginx to apply the changes
        systemctl reload nginx
        echo "Nginx configuration updated and reloaded successfully."
    else
        echo "Nginx configuration test failed. Please check your configuration for errors."
    fi
else
    echo "Nginx configuration file not found at $NGINX_CONFIG. Please make sure the path is correct."
fi
