#!/usr/bin/env bash
# Update the package list and install Nginx with automatic "yes" answers to prompts
sudo apt-get update
sudo apt-get install -y nginx

# Get the hostname of the server
hostname=$(hostname)

# Create a custom Nginx configuration file
sudo bash -c "cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
        add_header X-Served-By $hostname; # Add the custom header with the server's hostname
    }
}
EOF"

# Restart Nginx to apply changes
sudo systemctl restart nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
