#!/usr/bin/env bash
#This script installs and configures UFW to allow connections on poets 22, 80 and 443
sudo apt-get update
sudo apt-get install ufw
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw reload
