#!/usr/bin/env bash
#This script installs and configures UFW to allow connections on poets 22, 80 and 443
sudo apt-get update
sudo apt-get install ufw
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh/tcp
sudo ufw allow https/tcp
sudo ufw allow http/tcp
sudo ufw reload
